/* hed_themes: catalogue of runtime-swappable colour schemes.
 *
 * Registers each theme under its display name (`tokyo-night`, `gruvbox`,
 * `dracula`, `catppuccin-mocha`, `nord`, `rose-pine`) but does not
 * activate any. Pick one from config_init or at runtime:
 *
 *     plugin_load(&plugin_hed_themes, 1);
 *     theme_activate("tokyo-night");          // or :theme tokyo-night
 *
 * Palettes live in themes.c (generated by scripts/gen_themes.py). To add
 * a new theme, edit the THEMES dict in that script and re-run it. */

#include "hed.h"
#include "treesitter/theme.h"

void hed_themes_register_all(void); /* themes.c (generated) */

static int hed_themes_init(void) {
    if (!&theme_register) {
        log_msg("hed_themes: theme API unavailable (treesitter not built?)");
        return 0;
    }
    hed_themes_register_all();
    return 0;
}

const Plugin plugin_hed_themes = {
    .name   = "hed-themes",
    .desc   = "catalogue of runtime-swappable colour schemes",
    .init   = hed_themes_init,
    .deinit = NULL,
};
