/* Generated by scripts/gen_themes.py — do not edit by hand.
 *
 * To add or refresh themes, edit scripts/gen_themes.py and re-run it.
 * Browse https://dotfyle.com/neovim/colorscheme/top for ideas. */

#include "treesitter/theme.h"

static void apply_tokyo_night(void) {
    theme_palette_set("string", "\x1b[38;2;158;206;106m");
    theme_palette_set("comment", "\x1b[38;2;86;95;137m");
    theme_palette_set("variable", "\x1b[38;2;192;202;245m");
    theme_palette_set("constant", "\x1b[38;2;224;175;104m");
    theme_palette_set("number", "\x1b[38;2;255;158;100m");
    theme_palette_set("keyword", "\x1b[38;2;187;154;247m");
    theme_palette_set("type", "\x1b[38;2;42;195;222m");
    theme_palette_set("function", "\x1b[38;2;122;162;247m");
    theme_palette_set("attribute", "\x1b[38;2;187;154;247m");
    theme_palette_set("label", "\x1b[38;2;224;108;117m");
    theme_palette_set("operator", "\x1b[38;2;144;153;174m");
    theme_palette_set("punctuation", "\x1b[38;2;65;72;104m");
    theme_palette_set("title", "\x1b[1;38;2;192;202;245m");
    theme_palette_set("uri", "\x1b[4;38;2;122;162;247m");
    theme_palette_set("diag.error", "\x1b[38;2;247;118;142m");
    theme_palette_set("diag.warn", "\x1b[38;2;224;175;104m");
    theme_palette_set("diag.note", "\x1b[38;2;122;162;247m");
}

static void apply_gruvbox(void) {
    theme_palette_set("string", "\x1b[38;2;184;187;38m");
    theme_palette_set("comment", "\x1b[38;2;146;131;116m");
    theme_palette_set("variable", "\x1b[38;2;235;219;178m");
    theme_palette_set("constant", "\x1b[38;2;211;134;155m");
    theme_palette_set("number", "\x1b[38;2;211;134;155m");
    theme_palette_set("keyword", "\x1b[38;2;251;73;52m");
    theme_palette_set("type", "\x1b[38;2;250;189;47m");
    theme_palette_set("function", "\x1b[38;2;184;187;38m");
    theme_palette_set("attribute", "\x1b[38;2;142;192;124m");
    theme_palette_set("label", "\x1b[38;2;254;128;25m");
    theme_palette_set("operator", "\x1b[38;2;168;153;132m");
    theme_palette_set("punctuation", "\x1b[38;2;124;111;100m");
    theme_palette_set("title", "\x1b[1;38;2;251;73;52m");
    theme_palette_set("uri", "\x1b[4;38;2;131;165;152m");
    theme_palette_set("diag.error", "\x1b[38;2;251;73;52m");
    theme_palette_set("diag.warn", "\x1b[38;2;250;189;47m");
    theme_palette_set("diag.note", "\x1b[38;2;131;165;152m");
}

static void apply_dracula(void) {
    theme_palette_set("string", "\x1b[38;2;241;250;140m");
    theme_palette_set("comment", "\x1b[38;2;98;114;164m");
    theme_palette_set("variable", "\x1b[38;2;248;248;242m");
    theme_palette_set("constant", "\x1b[38;2;189;147;249m");
    theme_palette_set("number", "\x1b[38;2;189;147;249m");
    theme_palette_set("keyword", "\x1b[38;2;255;121;198m");
    theme_palette_set("type", "\x1b[38;2;139;233;253m");
    theme_palette_set("function", "\x1b[38;2;80;250;123m");
    theme_palette_set("attribute", "\x1b[38;2;255;121;198m");
    theme_palette_set("label", "\x1b[38;2;255;184;108m");
    theme_palette_set("operator", "\x1b[38;2;255;121;198m");
    theme_palette_set("punctuation", "\x1b[38;2;98;114;164m");
    theme_palette_set("title", "\x1b[1;38;2;248;248;242m");
    theme_palette_set("uri", "\x1b[4;38;2;139;233;253m");
    theme_palette_set("diag.error", "\x1b[38;2;255;85;85m");
    theme_palette_set("diag.warn", "\x1b[38;2;255;184;108m");
    theme_palette_set("diag.note", "\x1b[38;2;139;233;253m");
}

static void apply_catppuccin_mocha(void) {
    theme_palette_set("string", "\x1b[38;2;166;227;161m");
    theme_palette_set("comment", "\x1b[38;2;108;112;134m");
    theme_palette_set("variable", "\x1b[38;2;205;214;244m");
    theme_palette_set("constant", "\x1b[38;2;250;179;135m");
    theme_palette_set("number", "\x1b[38;2;250;179;135m");
    theme_palette_set("keyword", "\x1b[38;2;203;166;247m");
    theme_palette_set("type", "\x1b[38;2;249;226;175m");
    theme_palette_set("function", "\x1b[38;2;137;180;250m");
    theme_palette_set("attribute", "\x1b[38;2;203;166;247m");
    theme_palette_set("label", "\x1b[38;2;243;139;168m");
    theme_palette_set("operator", "\x1b[38;2;148;226;213m");
    theme_palette_set("punctuation", "\x1b[38;2;108;112;134m");
    theme_palette_set("title", "\x1b[1;38;2;205;214;244m");
    theme_palette_set("uri", "\x1b[4;38;2;137;180;250m");
    theme_palette_set("diag.error", "\x1b[38;2;243;139;168m");
    theme_palette_set("diag.warn", "\x1b[38;2;249;226;175m");
    theme_palette_set("diag.note", "\x1b[38;2;137;220;235m");
}

static void apply_nord(void) {
    theme_palette_set("string", "\x1b[38;2;163;190;140m");
    theme_palette_set("comment", "\x1b[38;2;76;86;106m");
    theme_palette_set("variable", "\x1b[38;2;216;222;233m");
    theme_palette_set("constant", "\x1b[38;2;180;142;173m");
    theme_palette_set("number", "\x1b[38;2;180;142;173m");
    theme_palette_set("keyword", "\x1b[38;2;129;161;193m");
    theme_palette_set("type", "\x1b[38;2;143;188;187m");
    theme_palette_set("function", "\x1b[38;2;136;192;208m");
    theme_palette_set("attribute", "\x1b[38;2;129;161;193m");
    theme_palette_set("label", "\x1b[38;2;191;97;106m");
    theme_palette_set("operator", "\x1b[38;2;216;222;233m");
    theme_palette_set("punctuation", "\x1b[38;2;76;86;106m");
    theme_palette_set("title", "\x1b[1;38;2;236;239;244m");
    theme_palette_set("uri", "\x1b[4;38;2;136;192;208m");
    theme_palette_set("diag.error", "\x1b[38;2;191;97;106m");
    theme_palette_set("diag.warn", "\x1b[38;2;235;203;139m");
    theme_palette_set("diag.note", "\x1b[38;2;136;192;208m");
}

static void apply_rose_pine(void) {
    theme_palette_set("string", "\x1b[38;2;246;193;119m");
    theme_palette_set("comment", "\x1b[38;2;110;106;134m");
    theme_palette_set("variable", "\x1b[38;2;224;222;244m");
    theme_palette_set("constant", "\x1b[38;2;235;188;186m");
    theme_palette_set("number", "\x1b[38;2;235;188;186m");
    theme_palette_set("keyword", "\x1b[38;2;49;116;143m");
    theme_palette_set("type", "\x1b[38;2;196;167;231m");
    theme_palette_set("function", "\x1b[38;2;156;207;216m");
    theme_palette_set("attribute", "\x1b[38;2;196;167;231m");
    theme_palette_set("label", "\x1b[38;2;235;111;146m");
    theme_palette_set("operator", "\x1b[38;2;144;140;170m");
    theme_palette_set("punctuation", "\x1b[38;2;82;79;103m");
    theme_palette_set("title", "\x1b[1;38;2;224;222;244m");
    theme_palette_set("uri", "\x1b[4;38;2;156;207;216m");
    theme_palette_set("diag.error", "\x1b[38;2;235;111;146m");
    theme_palette_set("diag.warn", "\x1b[38;2;246;193;119m");
    theme_palette_set("diag.note", "\x1b[38;2;156;207;216m");
}

void hed_themes_register_all(void) {
    if (!&theme_register) return;
    theme_register("tokyo-night", apply_tokyo_night);
    theme_register("gruvbox", apply_gruvbox);
    theme_register("dracula", apply_dracula);
    theme_register("catppuccin-mocha", apply_catppuccin_mocha);
    theme_register("nord", apply_nord);
    theme_register("rose-pine", apply_rose_pine);
}
