#ifndef CTAGS_H
#define CTAGS_H

/*
 * CTAGS INTEGRATION
 * =================
 *
 * Simple ctags integration for goto definition functionality.
 * Uses a tags file generated by `ctags -R` with format:
 *   TAG  FILEPATH  REGEX_STRING
 *
 * Features:
 * - find_tag: Search for a tag in the tags file
 * - goto_tag: Jump to tag definition
 * - tag_exists: Check if a tag exists
 */

typedef struct {
    char *tag;      /* Tag name */
    char *file;     /* File path */
    char *pattern;  /* Search pattern/regex */
} TagEntry;

/*
 * Find a tag in the tags file
 *
 * Searches for the tag using ripgrep and returns the parsed entry.
 * Caller must free the returned TagEntry with tag_entry_free().
 *
 * @param tag_name - The tag to search for
 * @return TagEntry* on success, NULL if not found or on error
 */
TagEntry *find_tag(const char *tag_name);

/*
 * Jump to a tag definition
 *
 * Searches for the tag, opens the file, and positions cursor at the definition.
 *
 * @param tag_name - The tag to jump to (NULL to use word under cursor)
 * @return 1 on success, 0 on failure
 */
int goto_tag(const char *tag_name);

/*
 * Check if a tag exists in the tags file
 *
 * @param tag_name - The tag to check
 * @return 1 if tag exists, 0 otherwise
 */
int tag_exists(const char *tag_name);

/*
 * Free a TagEntry allocated by find_tag()
 *
 * @param entry - The entry to free
 */
void tag_entry_free(TagEntry *entry);

#endif /* CTAGS_H */
